package com.gadawski;

import com.gadawski.drools.*;
import com.gadawski.paho.*;

import java.time.DayOfWeek;
import java.time.LocalDate;

rule "Home automation rule"
    //timer (cron:* 0/60 * * * ?)
    //timer (cron:0/1 * * * * ?)
    when
        date : RuleDate(date.getDayOfWeek() == DayOfWeek.SUNDAY)
    then
        PushMessageUtil.send(29, 0.6);
end

package com.gadawski.rules;

import com.gadawski.drools.*;

rule "Generated rule number 1"
when
    day : RuleDate( day.getDayOfWeek() == DayOfWeek.SUNDAY )
    day : RuleDate( day.getHour() == 21 )
then
// perform relevant action
end