package com.gadawski.drools; 


rule "HA rule for day: MONDAY and hour: 0"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.MONDAY, day.getHour() == 0 )  
then
com.gadawski.paho.PushMessageUtil.send(18.3, 0.5);
end

rule "HA rule for day: MONDAY and hour: 1"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.MONDAY, day.getHour() == 1 )  
then
com.gadawski.paho.PushMessageUtil.send(18.3, 0.5);
end

rule "HA rule for day: MONDAY and hour: 2"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.MONDAY, day.getHour() == 2 )  
then
com.gadawski.paho.PushMessageUtil.send(18.3, 0.5);
end

rule "HA rule for day: MONDAY and hour: 3"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.MONDAY, day.getHour() == 3 )  
then
com.gadawski.paho.PushMessageUtil.send(18.3, 0.5);
end

rule "HA rule for day: MONDAY and hour: 4"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.MONDAY, day.getHour() == 4 )  
then
com.gadawski.paho.PushMessageUtil.send(18.5, 1.0);
end

rule "HA rule for day: MONDAY and hour: 5"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.MONDAY, day.getHour() == 5 )  
then
com.gadawski.paho.PushMessageUtil.send(18.0, 0.0);
end

rule "HA rule for day: MONDAY and hour: 6"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.MONDAY, day.getHour() == 6 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: MONDAY and hour: 7"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.MONDAY, day.getHour() == 7 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: MONDAY and hour: 8"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.MONDAY, day.getHour() == 8 )  
then
com.gadawski.paho.PushMessageUtil.send(18.3, 0.5);
end

rule "HA rule for day: MONDAY and hour: 9"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.MONDAY, day.getHour() == 9 )  
then
com.gadawski.paho.PushMessageUtil.send(18.0, 0.8);
end

rule "HA rule for day: MONDAY and hour: 10"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.MONDAY, day.getHour() == 10 )  
then
com.gadawski.paho.PushMessageUtil.send(18.0, 0.8);
end

rule "HA rule for day: MONDAY and hour: 11"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.MONDAY, day.getHour() == 11 )  
then
com.gadawski.paho.PushMessageUtil.send(18.0, 0.8);
end

rule "HA rule for day: MONDAY and hour: 12"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.MONDAY, day.getHour() == 12 )  
then
com.gadawski.paho.PushMessageUtil.send(18.0, 0.8);
end

rule "HA rule for day: MONDAY and hour: 13"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.MONDAY, day.getHour() == 13 )  
then
com.gadawski.paho.PushMessageUtil.send(18.3, 0.5);
end

rule "HA rule for day: MONDAY and hour: 14"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.MONDAY, day.getHour() == 14 )  
then
com.gadawski.paho.PushMessageUtil.send(18.3, 0.5);
end

rule "HA rule for day: MONDAY and hour: 15"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.MONDAY, day.getHour() == 15 )  
then
com.gadawski.paho.PushMessageUtil.send(18.3, 0.5);
end

rule "HA rule for day: MONDAY and hour: 16"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.MONDAY, day.getHour() == 16 )  
then
com.gadawski.paho.PushMessageUtil.send(18.0, 0.0);
end

rule "HA rule for day: MONDAY and hour: 17"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.MONDAY, day.getHour() == 17 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: MONDAY and hour: 18"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.MONDAY, day.getHour() == 18 )  
then
com.gadawski.paho.PushMessageUtil.send(20.8, 0.5);
end

rule "HA rule for day: MONDAY and hour: 19"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.MONDAY, day.getHour() == 19 )  
then
com.gadawski.paho.PushMessageUtil.send(20.8, 0.5);
end

rule "HA rule for day: MONDAY and hour: 20"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.MONDAY, day.getHour() == 20 )  
then
com.gadawski.paho.PushMessageUtil.send(21.5, 1.0);
end

rule "HA rule for day: MONDAY and hour: 21"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.MONDAY, day.getHour() == 21 )  
then
com.gadawski.paho.PushMessageUtil.send(21.5, 1.0);
end

rule "HA rule for day: MONDAY and hour: 22"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.MONDAY, day.getHour() == 22 )  
then
com.gadawski.paho.PushMessageUtil.send(21.3, 1.3);
end

rule "HA rule for day: MONDAY and hour: 23"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.MONDAY, day.getHour() == 23 )  
then
com.gadawski.paho.PushMessageUtil.send(21.5, 1.0);
end

rule "HA rule for day: TUESDAY and hour: 0"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.TUESDAY, day.getHour() == 0 )  
then
com.gadawski.paho.PushMessageUtil.send(18.0, 0.0);
end

rule "HA rule for day: TUESDAY and hour: 1"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.TUESDAY, day.getHour() == 1 )  
then
com.gadawski.paho.PushMessageUtil.send(18.0, 0.0);
end

rule "HA rule for day: TUESDAY and hour: 2"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.TUESDAY, day.getHour() == 2 )  
then
com.gadawski.paho.PushMessageUtil.send(18.0, 0.0);
end

rule "HA rule for day: TUESDAY and hour: 3"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.TUESDAY, day.getHour() == 3 )  
then
com.gadawski.paho.PushMessageUtil.send(18.0, 0.0);
end

rule "HA rule for day: TUESDAY and hour: 4"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.TUESDAY, day.getHour() == 4 )  
then
com.gadawski.paho.PushMessageUtil.send(18.0, 0.0);
end

rule "HA rule for day: TUESDAY and hour: 5"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.TUESDAY, day.getHour() == 5 )  
then
com.gadawski.paho.PushMessageUtil.send(18.0, 0.0);
end

rule "HA rule for day: TUESDAY and hour: 6"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.TUESDAY, day.getHour() == 6 )  
then
com.gadawski.paho.PushMessageUtil.send(22.0, 0.0);
end

rule "HA rule for day: TUESDAY and hour: 7"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.TUESDAY, day.getHour() == 7 )  
then
com.gadawski.paho.PushMessageUtil.send(21.8, 0.5);
end

rule "HA rule for day: TUESDAY and hour: 8"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.TUESDAY, day.getHour() == 8 )  
then
com.gadawski.paho.PushMessageUtil.send(18.5, 1.0);
end

rule "HA rule for day: TUESDAY and hour: 9"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.TUESDAY, day.getHour() == 9 )  
then
com.gadawski.paho.PushMessageUtil.send(18.3, 0.5);
end

rule "HA rule for day: TUESDAY and hour: 10"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.TUESDAY, day.getHour() == 10 )  
then
com.gadawski.paho.PushMessageUtil.send(18.0, 0.0);
end

rule "HA rule for day: TUESDAY and hour: 11"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.TUESDAY, day.getHour() == 11 )  
then
com.gadawski.paho.PushMessageUtil.send(18.0, 0.0);
end

rule "HA rule for day: TUESDAY and hour: 12"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.TUESDAY, day.getHour() == 12 )  
then
com.gadawski.paho.PushMessageUtil.send(18.3, 0.5);
end

rule "HA rule for day: TUESDAY and hour: 13"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.TUESDAY, day.getHour() == 13 )  
then
com.gadawski.paho.PushMessageUtil.send(18.5, 1.0);
end

rule "HA rule for day: TUESDAY and hour: 14"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.TUESDAY, day.getHour() == 14 )  
then
com.gadawski.paho.PushMessageUtil.send(18.5, 1.0);
end

rule "HA rule for day: TUESDAY and hour: 15"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.TUESDAY, day.getHour() == 15 )  
then
com.gadawski.paho.PushMessageUtil.send(18.8, 1.5);
end

rule "HA rule for day: TUESDAY and hour: 16"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.TUESDAY, day.getHour() == 16 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 2.0);
end

rule "HA rule for day: TUESDAY and hour: 17"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.TUESDAY, day.getHour() == 17 )  
then
com.gadawski.paho.PushMessageUtil.send(21.8, 0.5);
end

rule "HA rule for day: TUESDAY and hour: 18"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.TUESDAY, day.getHour() == 18 )  
then
com.gadawski.paho.PushMessageUtil.send(21.5, 1.0);
end

rule "HA rule for day: TUESDAY and hour: 19"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.TUESDAY, day.getHour() == 19 )  
then
com.gadawski.paho.PushMessageUtil.send(22.0, 0.0);
end

rule "HA rule for day: TUESDAY and hour: 20"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.TUESDAY, day.getHour() == 20 )  
then
com.gadawski.paho.PushMessageUtil.send(21.8, 0.5);
end

rule "HA rule for day: TUESDAY and hour: 21"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.TUESDAY, day.getHour() == 21 )  
then
com.gadawski.paho.PushMessageUtil.send(22.0, 0.0);
end

rule "HA rule for day: TUESDAY and hour: 22"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.TUESDAY, day.getHour() == 22 )  
then
com.gadawski.paho.PushMessageUtil.send(21.8, 0.5);
end

rule "HA rule for day: TUESDAY and hour: 23"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.TUESDAY, day.getHour() == 23 )  
then
com.gadawski.paho.PushMessageUtil.send(22.0, 0.0);
end

rule "HA rule for day: WEDNESDAY and hour: 0"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.WEDNESDAY, day.getHour() == 0 )  
then
com.gadawski.paho.PushMessageUtil.send(17.0, 0.0);
end

rule "HA rule for day: WEDNESDAY and hour: 1"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.WEDNESDAY, day.getHour() == 1 )  
then
com.gadawski.paho.PushMessageUtil.send(17.0, 0.0);
end

rule "HA rule for day: WEDNESDAY and hour: 2"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.WEDNESDAY, day.getHour() == 2 )  
then
com.gadawski.paho.PushMessageUtil.send(17.0, 0.0);
end

rule "HA rule for day: WEDNESDAY and hour: 3"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.WEDNESDAY, day.getHour() == 3 )  
then
com.gadawski.paho.PushMessageUtil.send(17.0, 0.0);
end

rule "HA rule for day: WEDNESDAY and hour: 4"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.WEDNESDAY, day.getHour() == 4 )  
then
com.gadawski.paho.PushMessageUtil.send(17.0, 0.0);
end

rule "HA rule for day: WEDNESDAY and hour: 5"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.WEDNESDAY, day.getHour() == 5 )  
then
com.gadawski.paho.PushMessageUtil.send(17.0, 0.0);
end

rule "HA rule for day: WEDNESDAY and hour: 6"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.WEDNESDAY, day.getHour() == 6 )  
then
com.gadawski.paho.PushMessageUtil.send(20.0, 0.0);
end

rule "HA rule for day: WEDNESDAY and hour: 7"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.WEDNESDAY, day.getHour() == 7 )  
then
com.gadawski.paho.PushMessageUtil.send(20.0, 0.0);
end

rule "HA rule for day: WEDNESDAY and hour: 8"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.WEDNESDAY, day.getHour() == 8 )  
then
com.gadawski.paho.PushMessageUtil.send(17.0, 0.0);
end

rule "HA rule for day: WEDNESDAY and hour: 9"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.WEDNESDAY, day.getHour() == 9 )  
then
com.gadawski.paho.PushMessageUtil.send(17.0, 0.0);
end

rule "HA rule for day: WEDNESDAY and hour: 10"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.WEDNESDAY, day.getHour() == 10 )  
then
com.gadawski.paho.PushMessageUtil.send(17.0, 0.0);
end

rule "HA rule for day: WEDNESDAY and hour: 11"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.WEDNESDAY, day.getHour() == 11 )  
then
com.gadawski.paho.PushMessageUtil.send(17.0, 0.0);
end

rule "HA rule for day: WEDNESDAY and hour: 12"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.WEDNESDAY, day.getHour() == 12 )  
then
com.gadawski.paho.PushMessageUtil.send(17.0, 0.0);
end

rule "HA rule for day: WEDNESDAY and hour: 13"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.WEDNESDAY, day.getHour() == 13 )  
then
com.gadawski.paho.PushMessageUtil.send(17.0, 0.0);
end

rule "HA rule for day: WEDNESDAY and hour: 14"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.WEDNESDAY, day.getHour() == 14 )  
then
com.gadawski.paho.PushMessageUtil.send(17.3, 0.5);
end

rule "HA rule for day: WEDNESDAY and hour: 15"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.WEDNESDAY, day.getHour() == 15 )  
then
com.gadawski.paho.PushMessageUtil.send(17.0, 0.0);
end

rule "HA rule for day: WEDNESDAY and hour: 16"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.WEDNESDAY, day.getHour() == 16 )  
then
com.gadawski.paho.PushMessageUtil.send(17.0, 0.0);
end

rule "HA rule for day: WEDNESDAY and hour: 17"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.WEDNESDAY, day.getHour() == 17 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: WEDNESDAY and hour: 18"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.WEDNESDAY, day.getHour() == 18 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: WEDNESDAY and hour: 19"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.WEDNESDAY, day.getHour() == 19 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: WEDNESDAY and hour: 20"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.WEDNESDAY, day.getHour() == 20 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: WEDNESDAY and hour: 21"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.WEDNESDAY, day.getHour() == 21 )  
then
com.gadawski.paho.PushMessageUtil.send(20.8, 0.5);
end

rule "HA rule for day: WEDNESDAY and hour: 22"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.WEDNESDAY, day.getHour() == 22 )  
then
com.gadawski.paho.PushMessageUtil.send(20.8, 0.5);
end

rule "HA rule for day: WEDNESDAY and hour: 23"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.WEDNESDAY, day.getHour() == 23 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: THURSDAY and hour: 0"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.THURSDAY, day.getHour() == 0 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: THURSDAY and hour: 1"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.THURSDAY, day.getHour() == 1 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: THURSDAY and hour: 2"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.THURSDAY, day.getHour() == 2 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: THURSDAY and hour: 3"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.THURSDAY, day.getHour() == 3 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: THURSDAY and hour: 4"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.THURSDAY, day.getHour() == 4 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: THURSDAY and hour: 5"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.THURSDAY, day.getHour() == 5 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: THURSDAY and hour: 6"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.THURSDAY, day.getHour() == 6 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: THURSDAY and hour: 7"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.THURSDAY, day.getHour() == 7 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: THURSDAY and hour: 8"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.THURSDAY, day.getHour() == 8 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: THURSDAY and hour: 9"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.THURSDAY, day.getHour() == 9 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: THURSDAY and hour: 10"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.THURSDAY, day.getHour() == 10 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: THURSDAY and hour: 11"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.THURSDAY, day.getHour() == 11 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: THURSDAY and hour: 12"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.THURSDAY, day.getHour() == 12 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: THURSDAY and hour: 13"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.THURSDAY, day.getHour() == 13 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: THURSDAY and hour: 14"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.THURSDAY, day.getHour() == 14 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: THURSDAY and hour: 15"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.THURSDAY, day.getHour() == 15 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: THURSDAY and hour: 16"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.THURSDAY, day.getHour() == 16 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: THURSDAY and hour: 17"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.THURSDAY, day.getHour() == 17 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: THURSDAY and hour: 18"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.THURSDAY, day.getHour() == 18 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: THURSDAY and hour: 19"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.THURSDAY, day.getHour() == 19 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: THURSDAY and hour: 20"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.THURSDAY, day.getHour() == 20 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: THURSDAY and hour: 21"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.THURSDAY, day.getHour() == 21 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: THURSDAY and hour: 22"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.THURSDAY, day.getHour() == 22 )  
then
com.gadawski.paho.PushMessageUtil.send(20.8, 1.5);
end

rule "HA rule for day: THURSDAY and hour: 23"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.THURSDAY, day.getHour() == 23 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: FRIDAY and hour: 0"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.FRIDAY, day.getHour() == 0 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: FRIDAY and hour: 1"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.FRIDAY, day.getHour() == 1 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: FRIDAY and hour: 2"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.FRIDAY, day.getHour() == 2 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: FRIDAY and hour: 3"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.FRIDAY, day.getHour() == 3 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: FRIDAY and hour: 4"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.FRIDAY, day.getHour() == 4 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: FRIDAY and hour: 5"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.FRIDAY, day.getHour() == 5 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: FRIDAY and hour: 6"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.FRIDAY, day.getHour() == 6 )  
then
com.gadawski.paho.PushMessageUtil.send(20.0, 0.0);
end

rule "HA rule for day: FRIDAY and hour: 7"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.FRIDAY, day.getHour() == 7 )  
then
com.gadawski.paho.PushMessageUtil.send(20.0, 0.0);
end

rule "HA rule for day: FRIDAY and hour: 8"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.FRIDAY, day.getHour() == 8 )  
then
com.gadawski.paho.PushMessageUtil.send(20.0, 0.0);
end

rule "HA rule for day: FRIDAY and hour: 9"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.FRIDAY, day.getHour() == 9 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: FRIDAY and hour: 10"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.FRIDAY, day.getHour() == 10 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: FRIDAY and hour: 11"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.FRIDAY, day.getHour() == 11 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: FRIDAY and hour: 12"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.FRIDAY, day.getHour() == 12 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: FRIDAY and hour: 13"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.FRIDAY, day.getHour() == 13 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: FRIDAY and hour: 14"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.FRIDAY, day.getHour() == 14 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: FRIDAY and hour: 15"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.FRIDAY, day.getHour() == 15 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: FRIDAY and hour: 16"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.FRIDAY, day.getHour() == 16 )  
then
com.gadawski.paho.PushMessageUtil.send(20.0, 0.0);
end

rule "HA rule for day: FRIDAY and hour: 17"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.FRIDAY, day.getHour() == 17 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: FRIDAY and hour: 18"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.FRIDAY, day.getHour() == 18 )  
then
com.gadawski.paho.PushMessageUtil.send(22.0, 0.0);
end

rule "HA rule for day: FRIDAY and hour: 19"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.FRIDAY, day.getHour() == 19 )  
then
com.gadawski.paho.PushMessageUtil.send(22.0, 0.0);
end

rule "HA rule for day: FRIDAY and hour: 20"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.FRIDAY, day.getHour() == 20 )  
then
com.gadawski.paho.PushMessageUtil.send(22.0, 0.0);
end

rule "HA rule for day: FRIDAY and hour: 21"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.FRIDAY, day.getHour() == 21 )  
then
com.gadawski.paho.PushMessageUtil.send(22.0, 0.0);
end

rule "HA rule for day: FRIDAY and hour: 22"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.FRIDAY, day.getHour() == 22 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: FRIDAY and hour: 23"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.FRIDAY, day.getHour() == 23 )  
then
com.gadawski.paho.PushMessageUtil.send(20.0, 0.0);
end

rule "HA rule for day: SATURDAY and hour: 0"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SATURDAY, day.getHour() == 0 )  
then
com.gadawski.paho.PushMessageUtil.send(18.0, 0.0);
end

rule "HA rule for day: SATURDAY and hour: 1"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SATURDAY, day.getHour() == 1 )  
then
com.gadawski.paho.PushMessageUtil.send(18.0, 0.0);
end

rule "HA rule for day: SATURDAY and hour: 2"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SATURDAY, day.getHour() == 2 )  
then
com.gadawski.paho.PushMessageUtil.send(18.0, 0.0);
end

rule "HA rule for day: SATURDAY and hour: 3"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SATURDAY, day.getHour() == 3 )  
then
com.gadawski.paho.PushMessageUtil.send(18.0, 0.0);
end

rule "HA rule for day: SATURDAY and hour: 4"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SATURDAY, day.getHour() == 4 )  
then
com.gadawski.paho.PushMessageUtil.send(18.0, 0.0);
end

rule "HA rule for day: SATURDAY and hour: 5"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SATURDAY, day.getHour() == 5 )  
then
com.gadawski.paho.PushMessageUtil.send(18.0, 0.0);
end

rule "HA rule for day: SATURDAY and hour: 6"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SATURDAY, day.getHour() == 6 )  
then
com.gadawski.paho.PushMessageUtil.send(18.0, 0.0);
end

rule "HA rule for day: SATURDAY and hour: 7"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SATURDAY, day.getHour() == 7 )  
then
com.gadawski.paho.PushMessageUtil.send(18.0, 0.0);
end

rule "HA rule for day: SATURDAY and hour: 8"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SATURDAY, day.getHour() == 8 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: SATURDAY and hour: 9"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SATURDAY, day.getHour() == 9 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: SATURDAY and hour: 10"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SATURDAY, day.getHour() == 10 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: SATURDAY and hour: 11"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SATURDAY, day.getHour() == 11 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: SATURDAY and hour: 12"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SATURDAY, day.getHour() == 12 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: SATURDAY and hour: 13"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SATURDAY, day.getHour() == 13 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: SATURDAY and hour: 14"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SATURDAY, day.getHour() == 14 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: SATURDAY and hour: 15"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SATURDAY, day.getHour() == 15 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: SATURDAY and hour: 16"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SATURDAY, day.getHour() == 16 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: SATURDAY and hour: 17"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SATURDAY, day.getHour() == 17 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: SATURDAY and hour: 18"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SATURDAY, day.getHour() == 18 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: SATURDAY and hour: 19"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SATURDAY, day.getHour() == 19 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: SATURDAY and hour: 20"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SATURDAY, day.getHour() == 20 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: SATURDAY and hour: 21"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SATURDAY, day.getHour() == 21 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: SATURDAY and hour: 22"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SATURDAY, day.getHour() == 22 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: SATURDAY and hour: 23"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SATURDAY, day.getHour() == 23 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: SUNDAY and hour: 0"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SUNDAY, day.getHour() == 0 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: SUNDAY and hour: 1"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SUNDAY, day.getHour() == 1 )  
then
com.gadawski.paho.PushMessageUtil.send(18.0, 0.0);
end

rule "HA rule for day: SUNDAY and hour: 2"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SUNDAY, day.getHour() == 2 )  
then
com.gadawski.paho.PushMessageUtil.send(18.0, 0.0);
end

rule "HA rule for day: SUNDAY and hour: 3"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SUNDAY, day.getHour() == 3 )  
then
com.gadawski.paho.PushMessageUtil.send(18.0, 0.0);
end

rule "HA rule for day: SUNDAY and hour: 4"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SUNDAY, day.getHour() == 4 )  
then
com.gadawski.paho.PushMessageUtil.send(18.0, 0.0);
end

rule "HA rule for day: SUNDAY and hour: 5"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SUNDAY, day.getHour() == 5 )  
then
com.gadawski.paho.PushMessageUtil.send(18.0, 0.0);
end

rule "HA rule for day: SUNDAY and hour: 6"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SUNDAY, day.getHour() == 6 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: SUNDAY and hour: 7"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SUNDAY, day.getHour() == 7 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: SUNDAY and hour: 8"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SUNDAY, day.getHour() == 8 )  
then
com.gadawski.paho.PushMessageUtil.send(20.0, 0.0);
end

rule "HA rule for day: SUNDAY and hour: 9"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SUNDAY, day.getHour() == 9 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: SUNDAY and hour: 10"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SUNDAY, day.getHour() == 10 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: SUNDAY and hour: 11"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SUNDAY, day.getHour() == 11 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: SUNDAY and hour: 12"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SUNDAY, day.getHour() == 12 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: SUNDAY and hour: 13"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SUNDAY, day.getHour() == 13 )  
then
com.gadawski.paho.PushMessageUtil.send(22.0, 0.0);
end

rule "HA rule for day: SUNDAY and hour: 14"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SUNDAY, day.getHour() == 14 )  
then
com.gadawski.paho.PushMessageUtil.send(22.0, 0.0);
end

rule "HA rule for day: SUNDAY and hour: 15"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SUNDAY, day.getHour() == 15 )  
then
com.gadawski.paho.PushMessageUtil.send(22.0, 0.0);
end

rule "HA rule for day: SUNDAY and hour: 16"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SUNDAY, day.getHour() == 16 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: SUNDAY and hour: 17"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SUNDAY, day.getHour() == 17 )  
then
com.gadawski.paho.PushMessageUtil.send(21.0, 0.0);
end

rule "HA rule for day: SUNDAY and hour: 18"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SUNDAY, day.getHour() == 18 )  
then
com.gadawski.paho.PushMessageUtil.send(22.0, 0.0);
end

rule "HA rule for day: SUNDAY and hour: 19"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SUNDAY, day.getHour() == 19 )  
then
com.gadawski.paho.PushMessageUtil.send(22.0, 0.0);
end

rule "HA rule for day: SUNDAY and hour: 20"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SUNDAY, day.getHour() == 20 )  
then
com.gadawski.paho.PushMessageUtil.send(22.0, 0.0);
end

rule "HA rule for day: SUNDAY and hour: 21"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SUNDAY, day.getHour() == 21 )  
then
com.gadawski.paho.PushMessageUtil.send(20.0, 0.0);
end

rule "HA rule for day: SUNDAY and hour: 22"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SUNDAY, day.getHour() == 22 )  
then
com.gadawski.paho.PushMessageUtil.send(19.0, 0.0);
end

rule "HA rule for day: SUNDAY and hour: 23"
when
    day : com.gadawski.drools.RuleDate( day.getDayOfWeek() == java.time.DayOfWeek.SUNDAY, day.getHour() == 23 )  
then
com.gadawski.paho.PushMessageUtil.send(18.0, 0.0);
end


